### PR TITLE
Add Advisors

### PR DESCRIPTION
**Pull request by zweistein1326**

### CODE REVIEW

**Comment by welvin21** [comment]
@zweistein1326 I'll help rebasing this to `master` before reviewing.

**Review by welvin21 — COMMENTED** [review]
@zweistein1326 Looking great! A few design inputs: 

1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
2. Would be great if we have different card design compared to that for members.

Would love to hear your opinions on those.

**Comment by welvin21** [comment]
> @zweistein1326 Looking great! A few design inputs:
> 
> 1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
> 2. Would be great if we have different card design compared to that for members.
> 
> Would love to hear your opinions on those.

@zweistein1326 I separated the `advisors` component to a designated page, check it out

**Comment by zweistein1326** [comment]
I feel like redirecting to another page is breaking the flow of a single page design. Maybe we can redirect to their social and skip their descriptions. What do you think?

**Comment by zweistein1326** [comment]
> > @zweistein1326 Looking great! A few design inputs:
> > 
> > 1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
> > 2. Would be great if we have different card design compared to that for members.
> > 
> > Would love to hear your opinions on those.
> 
> @zweistein1326 I separated the `advisors` component to a designated page, check it out

@welvin21 I feel like redirecting to another page is breaking the flow of a single page design and we'll have to change all the routes. Maybe we can redirect to their social and skip their descriptions to save space. I agree we should change the design for their pictures. What do you think?

**Comment by welvin21** [comment]
> > > @zweistein1326 Looking great! A few design inputs:
> > > 
> > > 1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
> > > 2. Would be great if we have different card design compared to that for members.
> > > 
> > > Would love to hear your opinions on those.
> > 
> > 
> > @zweistein1326 I separated the `advisors` component to a designated page, check it out
> 
> @welvin21 I feel like redirecting to another page is breaking the flow of a single page design and we'll have to change all the routes. Maybe we can redirect to their social and skip their descriptions to save space. I agree we should change the design for their pictures. What do you think?

@zweistein1326 yeah that works too, i'll play around with the new design a bit. will let you know once it's done

**Comment by zweistein1326** [comment]
> > > > @zweistein1326 Looking great! A few design inputs:
> > > > 
> > > > 1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
> > > > 2. Would be great if we have different card design compared to that for members.
> > > > 
> > > > Would love to hear your opinions on those.
> > > 
> > > 
> > > @zweistein1326 I separated the `advisors` component to a designated page, check it out
> > 
> > 
> > @welvin21 I feel like redirecting to another page is breaking the flow of a single page design and we'll have to change all the routes. Maybe we can redirect to their social and skip their descriptions to save space. I agree we should change the design for their pictures. What do you think?
> 
> @zweistein1326 yeah that works too, i'll play around with the new design a bit. will let you know once it's done

@welvin21 have we decided the design for advisor tile yet?

**Comment by welvin21** [comment]
> > > > > @zweistein1326 Looking great! A few design inputs:
> > > > > 
> > > > > 1. Let's move `advisors` to a separate page? `hacksochku.github.io.../advisors`? I feel like it's taken too much space.
> > > > > 2. Would be great if we have different card design compared to that for members.
> > > > > 
> > > > > Would love to hear your opinions on those.
> > > > 
> > > > 
> > > > @zweistein1326 I separated the `advisors` component to a designated page, check it out
> > > 
> > > 
> > > @welvin21 I feel like redirecting to another page is breaking the flow of a single page design and we'll have to change all the routes. Maybe we can redirect to their social and skip their descriptions to save space. I agree we should change the design for their pictures. What do you think?
> > 
> > 
> > @zweistein1326 yeah that works too, i'll play around with the new design a bit. will let you know once it's done
> 
> @welvin21 have we decided the design for advisor tile yet?

@zweistein1326 we have 2 designs as of now, the one you proposed, and the one I have in mind. I'll code that tonight

**Pull request merged**
